### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by zhangwen9229**
Dear maintainer:
    I want to make js-sdk for cosmos.I ready wrap some restful apis code.What's your opinions?I would like to continue my work to wrap all restful apis in this project.

                                                                                                                                                      By:QOSGroup

### CODE REVIEW

**Comment by zhangwen9229** [comment]
@ethanfrey
@rigelrozanski

**Comment by ethanfrey** [comment]
Hi, I am no longer working with cosmos, and as far as I know this project is dead.
This worked with the rest api from cosmos-sdk 0.8.0, which is much different than current cosmos-sdk 0.25.0.

I think @faboweb could direct you to the current js client for cosmos-sdk

**Comment by zhangwen9229** [comment]
> Hi, I am no longer working with cosmos, and as far as I know this project is dead.
> This worked with the rest api from cosmos-sdk 0.8.0, which is much different than current cosmos-sdk 0.25.0.
> 
> I think @faboweb could direct you to the current js client for cosmos-sdk

@ethanfrey thank you.
I'm working with latest cosmos-sdk.

**Comment by faboweb** [comment]
Hi! Great seeing you interested in the Cosmos ecosystem and greatly encouraging you to contribute.
As Ethan suggested I think you should start with getting up to speed on the latest SDK and its REST endpoints. We have a documentation on them here: https://cosmos-staging.interblock.io/rpc/.
The wrapper we use for Voyager looks like this: https://github.com/cosmos/voyager/blob/develop/app/src/renderer/connectors/lcdClient.js
Can you give me a quick summary of what you want to achieve with this lib so I can help you better? Also feel free to ask any question.

**Comment by zhangwen9229** [comment]
@faboweb thank you for the information! I see voyager as a cosmos specific PC client, my intention was to build a more general sdk which coders can work with broadly.  I'm also looking forward to your opinion on mobile wallets' case, which structure will you sugguest? full node or lcd?

**Comment by ethanfrey** [comment]
@zhangwen9229 That is an ambitious and larger task.

If I understand it, you want to build a js client that can work with any app built on top of cosmos-sdk. Should it be pure js and talk to tendermint directly? Or use the lcd? How would it get the app-specific endpoints?

This is a big design undertaking. I have been doing some work, blocked a bit on amino-js support. Irisnet has been doing good work on this front as well, and I think a few others.

If you have a clear use-case or design, I am happy to discuss this in more detail.
If your main case is to build a client specific to qoschain, that is a simper undertaking (as you have control of the backend as well, not to support "every cosmos-sdk app").

I am sure there is a lot of client side code that can be shared between various cosmos-sdk based projects

**Comment by tedyyan** [comment]
Yes, it's a challenge project.  @ethanfrey @faboweb 
Actually, our design is that lcd would be embedded in app and it could talk with any full node. And there is alliance of full nodes and the full node provider could get some revnew from the transaction fee or other benifit. It's a long term goal. What do you think about it?
If the goal is achievable, I think lcd should be implemented by js is a good way. What did block your work, could you share some code? I use to do amino js lib, https://github.com/TanNgocDo/Js-Amino. It's not only for qoschain, it's for decentralized light wallet app.

**Comment by ethanfrey** [comment]
> If the goal is achievable, I think lcd should be implemented by js is a good way. What did block your work, could you share some code?

Basically, I have a library working for a few other chains with different serialization. The issue for cosmos was 1) encode/decode go-amino 2) properly sign transactions.

I saw the code from Js-Amino a while ago, maybe I should check again if it is more complete.

I agree a pure js client side is much more accessible than golang.
Swift or Java would also be interesting SDKs for mobile, but golang has almost no foothold in any gui programming

**Comment by tedyyan** [comment]
@faboweb @ethanfrey 
Thanks for your response. l will give it a shot to run a lcd in JS. Yes, the key is the app-specific endpoints, it looks like decentralized wallet app can not avoid to require a centralized directory service which is running by an authrized entity or community which could provide a trusted and security endpoint although it won't need to provide a full node. So it's low resource cost but high security node. I think wallet app factory should provide this kind of node.

**Pull request closed without merging**
